// FIX: Define and export all shared types to be used across the application.
// This file should only contain type definitions, not business logic.

export type Page = 'landing' | 'planner' | 'what-is' | 'about' | 'contact' | 'privacy' | 'disclaimer' | 'gdpr' | 'copyright' | 'pricing' | 'scheduling' | 'project_selection' | 'hot_execution_review' | 'admin_dashboard' | 'user_management' | 'voir-la-demo' | 'ebook' | 'data_management' | 'what_if_scenario' | 'ai_copilot' | 'live_navigation' | 'project_hub';

export interface PDRItem {
  id: string; // Internal id for managing edits
  OT: string | number;
  sparePart: string;
  unite: string;
  type: string;
  qty: number;
  priceU: number;
  totalPrice: number;
  readiness: number; // 0 or 1
  dueDate: string | null;
  comment?: string;
  status?: 'Awaiting Process' | 'Active Tenders' | 'Inventory Assets';
  criticity?: number; // 0 = standard, 1 = critical
}

export interface RawTask extends Record<string, any> { }

export interface SchedulingTaskData extends Record<string, any> {
  // Input from Excel - can be string or number from parser
  id: number;
  DUREE: number;
  DISCIPLINE: string;
  "Nom Equipement": string;
  FAMILLE: string;
  "GLOBAL TASKS": string;
  "Type de Maintenance": string;
  EFFECTIF: number;
  "Heures-Homme": number;
  Préparatifs: string;
  AVIS: string | number;
  OT: string | number;
  "COMMENTAIRE HSE": string | number;
  "Scaffolding Required"?: number;
  "Scaffolding Readiness"?: number;
  "Handling required"?: number;
  "Handling Readiness"?: number;
  "permis Levage"?: number;
  "permis Levage Readiness"?: number;
  "permis Travail Hauteur"?: number;
  "permis Travail Hauteur Readiness"?: number;
  "permis Feu"?: number;
  "permis Feu Readiness"?: number;
  "permis Penetration"?: number;
  "permis Penetration Readiness"?: number;
  "permis Excavation"?: number;
  "permis Excavation Readiness"?: number;
  "MO Required"?: number;
  "MO Readiness"?: number;
  "ADRPT Required"?: number;
  "ADRPT Readiness"?: number;
  "THR"?: number;
  sequenceOrder: number | null;

  // Output - generated by user
  DAY: string | null;
  "TYPE D'EQUIPE": string | null; // Now an output, assigned by user in modal
  "EQUIPE NUMBER": number | null;
  "MAX HOUR": number | null;
  "START DATE": Date | null;
  "END DATE": Date | null;
  predecessor: number[] | null; // task ids
  // FIX: Added temporary properties for parsing name-based dependencies.
  predecessorsByName?: string[];
  successorsByName?: string[];
  isScheduled: boolean;
  isLastForTeam?: boolean;
  isCritical?: boolean;
  isKeyEvent?: boolean;
  multiDisciplineId?: string;
  Latitude?: string | number;
  Longitude?: string | number;

  // Attached PDR (Spare parts) Items
  pdrItems?: PDRItem[];

  // Permit and Procedure Fields (Older fields kept for compatibility)
  ADRPT?: number; // 1 for Yes, 0 for No, -1 for N/A
  modeOperatoire?: number;
  permisTravailHauteur?: number;
  permisFeu?: number;
  permisPenetration?: number;
  permisLevage?: number;
  permisExcavation?: number;

  // METADATA FOR DATA HEALTH (New)
  meta?: {
    rowNumber: number;
    originalDuration: any;
    originalManpower: any;
    parsingWarnings: string[];
    isGarbage?: boolean;
  };

  // Cost Control Fields
  ZONE?: string;
  COMPANY?: string;
  "PRICE FOR HH"?: number;
  "MANUAL PRICE"?: number;
  "Scaffolding manual Price"?: number;
  "Handling manual Price"?: number;
  "PDR COST"?: number;
  "TOTAL TASK COST"?: number;

  // New multi-sheet domain fields (populated by OT linking)
  "POSTE NUMBER"?: number | string;
  QT?: number;
  "Additional Cost"?: number;
  "POSTE DESCRIPTION"?: string;
  "COST_TYPE"?: 'HH' | 'QT' | string; // 'HH' = Heures-Homme × Price U, 'QT' = QT × Price U
  "TASK_COST"?: number;      // (HH or QT) × Price U + Additional Cost
  "MO_HH_COST"?: number;     // TASK_COST when COST_TYPE === 'HH'
  "PRESTATION_COST"?: number; // TASK_COST when COST_TYPE !== 'HH'
  "SCAFFOLDING_COST"?: number; // from Scaffolding sheet (always QT-based)
  "HANDLING_COST"?: number;    // from Handling sheet (hours-based)
  "TOTAL_COST"?: number;       // TASK + SCAFFOLDING + HANDLING + PDR

  // Linked domain records (populated after OT join)
  scaffoldingRecords?: ScaffoldingRecord[];
  handlingRecords?: HandlingRecord[];
  permitRecords?: PermitRecord[];
  simopsRecords?: SimopsRecord[];
}

export interface ShutdownParams {
  shutdownStart: string;
  shutdownEnd: string;
  consignation: number;
  deconsignation: number;
  combustion: number | CombustionParams;
  workingHoursPerDay: 8 | 12 | 24;
}

export interface SchedulingFilters {
  discipline: string[];
  equipment: string[];
  family: string[];
  maintenanceType: string[];
  showUnscheduledOnly: boolean;
  assignedTeam: string[];
  showScheduledOnly?: boolean;
  multiDisciplineOnly?: boolean;
}

export interface SchedulingPageState {
  tasks: SchedulingTaskData[];
  mapTasks?: SchedulingTaskData[];
  shutdownParams: ShutdownParams;
  currentFile: File;
  filters: SchedulingFilters;
  dailyDurationLimit: number;
  evaluationData?: EvaluationData;
  costData?: CompanyCost[];        // Legacy: single-rate COSTE sheet
  costHubEntries?: CostHubEntry[]; // New: multi-rate Cost Hub sheet
  scaffoldingRecords?: ScaffoldingRecord[];
  handlingRecords?: HandlingRecord[];
  permitRecords?: PermitRecord[];
  simopsRecords?: SimopsRecord[];
  pdrItems: PDRItem[];
}

/** Legacy single-rate cost model (kept for backward compat) */
export interface CompanyCost {
  company: string;
  pricePerHour: number;
}

/** New Poste-based cost hub entry (from 'Cost Hub' sheet) */
export interface CostHubEntry {
  company: string;
  posteNumber: number | string;
  posteDescription: string;
  priceU: number;
  /** 'HH' = use Heures-Homme × Price U; anything else / undefined = use QT × Price U */
  costType?: 'HH' | 'QT' | string;
}

export interface ScaffoldingRecord {
  OT: string;
  company: string;
  readiness: number; // 1 = ready, 0 = not ready
  posteNumber: number | string;
  posteDescription?: string;
  QT: number;
  totalPrice?: number; // calculated or from sheet
  comment?: string;
}

export interface HandlingRecord {
  OT: string;
  company: string;
  handlingType: string;
  readiness: number; // 1 = ready, 0 = not ready
  posteNumber: number | string;
  posteDescription?: string;
  hours: number;
  additionalCost: number;
  totalPrice?: number; // calculated or from sheet
  comment?: string;
}

export interface PermitRecord {
  OT: string;
  permitName: string; // free text e.g. 'Permis de travail en hauteur'
  readiness: number;  // 1 = ready, 0 = not ready
}

export interface SimopsRecord {
  OT: string;
  simopsOT: string; // sibling OT that must run simultaneously
}


export interface Task {
  id: number;
  action: string;
  team: string;
  discipline: string; // FIX: Added explicit discipline field to avoid string splitting issues
  equipment: string;
  family: string;
  duration: number;
  manHours: number;
  manpower: number;
  predecessor: number[] | null;
  predecessorActions: string[];
  hasDeconsignationSuccessor: boolean;
  imperativeStart: boolean;
  sequenceOrder: number | null;
  ot?: string;
  avis?: string;
  isHighRisk: boolean;
  "Scaffolding Required"?: number;
  "Scaffolding Readiness"?: number;
  "Handling required"?: number;
  "Handling Readiness"?: number;
  "permis Levage"?: number;
  "permis Levage Readiness"?: number;
  "permis Travail Hauteur"?: number;
  "permis Travail Hauteur Readiness"?: number;
  "permis Feu"?: number;
  "permis Feu Readiness"?: number;
  "permis Penetration"?: number;
  "permis Penetration Readiness"?: number;
  "permis Excavation"?: number;
  "permis Excavation Readiness"?: number;
  "MO Required"?: number;
  "MO Readiness"?: number;
  "ADRPT Required"?: number;
  "ADRPT Readiness"?: number;
  permisTravailHauteur?: number;
  permisFeu?: number;
  permisPenetration?: number;
  permisLevage?: number;
  permisExcavation?: number;
  preparatifs?: string;
  "Préparatifs Readiness"?: number;
  isKeyEvent?: boolean;
  maintenanceType?: string;
  multiDisciplineId?: string;
  pdrItems?: PDRItem[]; // Attached spare parts

  // Cost Control Fields
  ZONE?: string;
  COMPANY?: string;
  "PRICE FOR HH"?: number;
  "MANUAL PRICE"?: number;
  "Scaffolding manual Price"?: number;
  "Handling manual Price"?: number;
  "PDR COST"?: number;
  "TOTAL TASK COST"?: number;
}

export interface ScheduledTask extends Task {
  startTime: Date;
  endTime: Date;
  isLate: boolean;
}

export interface CombustionParams {
  mode: 'parallel' | 'after_deconsignation';
  value: number; // in minutes
}

export interface AppParameters {
  shutdownStart: string;
  shutdownEnd: string;
  consignation: number;
  deconsignation: number;
  combustion: CombustionParams;
  demarrage: number; // in minutes
}

// New Interface for Data Health
export interface DataHealthIssue {
  taskId: number;
  rowNumber: number; // Real Excel Row
  taskName: string;
  field: string;
  value: number | string; // The value used by system
  originalValue: any; // The raw value from Excel
  reason: string;
  severity: 'critical' | 'warning';
}

export interface CalculationResults {
  kpis: {
    totalTasks: number;
    totalManHours: number;
    shutdownDurationHours: number;
    effectiveWorkHours: number;
  };
  peakResources: Record<string, number>;
  scheduledTasks: ScheduledTask[];
  scheduleEndDate: Date;
  maxWorkDate: Date;
  // Added Data Health Report
  dataHealth?: {
    status: 'clean' | 'warning' | 'critical';
    score: number;
    issues: DataHealthIssue[];
  };
  pdrItems?: PDRItem[]; // Keep track of spare parts
  simopsRecords?: SimopsRecord[]; // Keep track of SIMOPS data for reports
  thrTaskOTs?: string[]; // OTs of tasks flagged as THR
}

// FIX: Add 'Annuler' to TaskStatus type to support a third task status.
export type TaskStatus = 'À Faire' | 'En Cours' | 'Fait' | 'Non Fait' | 'Annuler';

export interface NonCompletionDetails {
  cause: string;
  criticality: string;
  counterMeasure: string;
  pilot: string;
}

export interface SlippageDetails {
  lostHours: number;
  cause: string[];
  preventiveAction: string[];
  pilot: string[];
}

export interface EvaluatedTaskData {
  actualStart: string;
  actualEnd: string;
  status: TaskStatus;
  nonCompletionDetails?: NonCompletionDetails;
  slippageDetails?: SlippageDetails;
  actualProgress?: number;      // Avancement Réel (%)
  actualRemainingTime?: number; // Temps restant Réel (h)
  isConfirmed?: boolean;       // Avancement validé par l'utilisateur
  actualManpower?: number;     // Ressources réelles utilisées (éditable dans l'évaluation)
}

export interface OngoingProgress {
  task: ScheduledTask;
  durationInPeriod: number;
  progressPlanned: number;
  progressActual: number;
  timeLeftPlanned: number;
  timeLeftActual: number;
  status: TaskStatus;
  actualEnd?: Date;
  actualDuration?: number;
  realAtteint?: number;       // Réel (Atteint) - Man-Hours
  tacticalRealization?: number; // Réalisation Tactique (%)
}

export interface TeamDetail {
  team: string;
  manpower: number;
  duration: number;
  manHours: number; // Calculated: manpower * duration
}

export interface SupplementaryTask {
  id: string;
  action: string;
  equipment: string;
  maintenanceType: 'Préventive' | 'Corrective';
  teamDetails: TeamDetail[];
  totalManHours: number;
  startDate?: string;
  endDate?: string;
  duration: number;
}

export interface GlobalSlippageEvent {
  id: string;
  eventDate: string;
  lostHours: number;
  cause: string;
  preventiveAction: string;
  pilot: string;
  imputation?: string;
}

export interface ChronologyEvent {
  id: string;
  label: string;
  plannedStart: string;
  plannedEnd: string;
  actualStart: string;
  actualEnd: string;
}

export interface EventDetail {
  id: string;
  dateTime: string;
  description: string;
}

export interface EvaluationData {
  actualShutdownStart: string;
  actualShutdownEnd: string;
  tasks: Record<number, EvaluatedTaskData>;
  supplementaryTasks: SupplementaryTask[];
  globalSlippageEvents: GlobalSlippageEvent[];
  chronology: ChronologyEvent[];
  incidentDetails: EventDetail[];
  accidentDetails: EventDetail[];
}

export interface ReportData {
  coverImage: string | null; // base64 data URL
  logo: string | null;       // base64 data URL
  title: string;
  preparedBy: string;
}

// FIX: Removed corrupted content and defined a proper interface for selected report pages.
export interface ReportPages {
  performanceChart: boolean;
  kpiCards: boolean;
  comparativeAnalysis: boolean;
  chronologySection: boolean;
  supplementaryTasks: boolean;
  slippageAnalysis: boolean;
  nonCompletedTasks: boolean;
  detailedLog: boolean;
  disciplineAnalysis: boolean;
  teamGauges: boolean;
  masterGantt: boolean;
}

// FIX: Added missing type definitions for Authentication and AI features.

export interface AIAnalysisResult {
  executiveSummary: {
    status: 'On Track' | 'At Risk' | 'Off Track';
    summaryText: string;
  };
  keyFindings: {
    type: 'positive' | 'negative';
    finding: string;
  }[];
  recommendations: string[];
  bottlenecks: string[];
}

export interface EvaluationKpis {
  plannedShutdownDuration: number;
  actualShutdownDuration: number;
  totalSlippage: number;
  completionRate: number;
  completedTasks: number;
  uncompletedTasks: number;
  totalPlannedTasks: number;
  supplementaryCharge: number;
  completionByDiscipline: Record<string, { completed: number, total: number }>;
  completionByTeam: Record<string, { completed: number, total: number }>;
  supplementaryTasksCount: number;
  slippageRate: number;
  supplementaryWorkRate: number;
  incidents: number;
  accidents: number;

  // --- NEW HOT REVIEW KPIS ---
  plannedGlobalProgress?: number; // Avancement global planifié
  actualGlobalProgress?: number;  // Avancement global réel
  plannedRealizationRate?: number; // Taux de réalisation (Plage) Planifié
  actualRealizationRate?: number;  // Taux de réalisation (Plage) Réel
  potentialSlippage?: number;      // Glissement Potentiel (Heures)
  timeRangeEvaluated?: string;    // Plage de Temps Évaluée (e.g., "17/12 09:00 - 18/12 02:00")
  extraWorkCharge?: number;         // Charge des travaux "Extra" (surplus d'effectif sur les travaux planifiés)
  plannedWorkCharge?: number;      // Charge des travaux planifiés (sur cette plage)
  supplementaryWorkCharge?: number; // Charge des travaux supplémentaires (sur cette plage)
  plannedWorkCount?: number;       // Nombre des travaux planifiés (sur cette plage)
  supplementaryWorkCount?: number; // Nombre des travaux supplémentaires (sur cette plage)

  // Comparisons/Ratios
  plannedVsSupplementaryCountRatio?: number;
  plannedVsSupplementaryChargeRatio?: number;
  plannedVsSupplementaryRateRatio?: number;

  // Resource Tracking
  supplementaryResourcesByDiscipline?: Record<string, number>;
  extraManHoursByDiscipline?: Record<string, number>;

  // Progress History for Line Graph
  progressHistory?: {
    timestamp: string;
    planned: number;
    actual: number;
  }[];
  criticalTaskName?: string; // Tâche responsable du glissement global
}

export interface CustomCriticalPath {
  id: string;
  name: string;
  start: string;
  end: string;
  color: string;
}

export type SortableHotReviewKeys = 'ot' | 'team' | 'action' | 'startTime' | 'endTime' | 'duration' | 'actualStart' | 'actualEnd' | 'actualDuration' | 'slippage';

export interface SlippageAnalysis {
  cause: string;
  actionPlan: string;
}

export interface HotReviewState {
  // Input values
  startDate: string;
  endDate: string;

  // Values for display/calculation
  displayedStartDate: string;
  displayedEndDate: string;

  dateFilteredTasks: ScheduledTask[];
  selectedFamily: string;
  selectedEquipment: string;
  selectedDiscipline: string;
  selectedTeam: string;
  searchTerm: string;
  slippageAnalysis: SlippageAnalysis;
  sortConfig: { key: SortableHotReviewKeys | null; direction: 'ascending' | 'descending' };
  manuallyIncludedTaskIds: number[];
}

export interface UserNotification {
  id: string;
  message: string;
  read: boolean;
  date: string;
  from: 'admin' | 'system';
}

export interface UserAccount {
  id: number;
  firstName: string;
  lastName: string;
  email: string;
  phone: string;
  username: string;
  password?: string;
  role: 'Manager' | 'Director' | 'Scheduler' | 'Guest' | 'admin' | 'user';
  status: 'Active' | 'Suspended' | 'Blocked';
  picture?: string;
  expiresAt?: string | null; // ISO Date String
  notifications?: UserNotification[];
}
