// services/licenseService.ts
// Local authentication — no Supabase, fully offline.
// Two flows:
//   1. Admin:  rachid / 123 → always works
//   2. Client: loads a .plxlicense file generated by you from the Admin Panel

import { validateLicenseFile } from './licenseEngine';

export interface LicenseSession {
  username: string;
  companyName: string;
  activationKey: string;
  expiresAt: Date;
  isAdmin: boolean;
  gracePeriodDays: number;
}

export interface LoginResult {
  success: boolean;
  session?: LicenseSession;
  error?: 'not_found' | 'wrong_password' | 'inactive' | 'network_error' | 'wrong_machine' | 'expired' | 'tampered' | 'invalid_format';
}

export interface UserProfile {
  username: string;
  passwordHash: string;
  licenseContent: string;
  createdAt: string;
}

/** Hash a password using Web Crypto SHA-256 */
async function hashPassword(password: string): Promise<string> {
  const msgBuffer = new TextEncoder().encode(password);
  const hashBuffer = await crypto.subtle.digest('SHA-256', msgBuffer);
  const hashArray = Array.from(new Uint8Array(hashBuffer));
  return hashArray.map(b => b.toString(16).padStart(2, '0')).join('');
}

/** Get the current machine ID from Electron */
export async function getMachineId(): Promise<string> {
  try {
    const id = await (window as any).electronAPI?.getMachineId?.();
    return id || 'DEV-MACHINE';
  } catch {
    return 'DEV-MACHINE';
  }
}

/** Admin login — hardcoded credentials. */
export async function loginAsAdmin(username: string, password: string): Promise<LoginResult> {
  if (username.toLowerCase().trim() === 'rachid' && password === '123') {
    return {
      success: true,
      session: {
        username: 'rachid',
        companyName: 'PlanneX Admin',
        activationKey: 'PLX-ADMIN-LOCAL',
        expiresAt: new Date(2100, 0, 1),
        isAdmin: true,
        gracePeriodDays: 7,
      },
    };
  }
  return { success: false, error: 'wrong_password' };
}

/** Check if user profile exists */
export async function hasUserProfile(): Promise<boolean> {
  try {
    const profile = await (window as any).electronAPI?.profileRead?.();
    return !!profile;
  } catch { return false; }
}

/** Client Login (with existing profile and password) */
export async function loginWithPassword(username: string, password: string): Promise<LoginResult> {
  try {
    const profile: UserProfile | null = await (window as any).electronAPI?.profileRead?.();
    if (!profile) return { success: false, error: 'not_found' };

    if (profile.username !== username.trim().toLowerCase()) return { success: false, error: 'not_found' };

    const hashed = await hashPassword(password);
    if (profile.passwordHash !== hashed) return { success: false, error: 'wrong_password' };

    // Now validate the saved license
    const machineId = await getMachineId();
    const result = await validateLicenseFile(profile.licenseContent, machineId);
    if (!result.valid) return { success: false, error: result.error };

    const p = result.payload!;
    return {
      success: true,
      session: {
        username: p.username,
        companyName: p.companyName,
        activationKey: 'PLX-CLIENT-LOCAL',
        expiresAt: new Date(p.expiresAt),
        isAdmin: false,
        gracePeriodDays: 0,
      }
    };
  } catch { return { success: false, error: 'invalid_format' }; }
}

/** Client Setup (after license validation, they set their username and password) */
export async function setupClientProfile(licenseContent: string, username: string, password: string): Promise<LoginResult> {
  const machineId = await getMachineId();
  const result = await validateLicenseFile(licenseContent, machineId);

  if (!result.valid) {
    return { success: false, error: result.error };
  }

  const p = result.payload!;
  
  // Save profile
  const passwordHash = await hashPassword(password);
  const profile: UserProfile = {
    username: username.trim().toLowerCase(),
    passwordHash,
    licenseContent,
    createdAt: new Date().toISOString()
  };

  try {
    await (window as any).electronAPI?.profileWrite?.(profile);
  } catch (e) {
    console.error("Failed to write profile", e);
  }

  return {
    success: true,
    session: {
      username: p.username, // Using the license username internally? Actually we use what they picked.
      companyName: p.companyName,
      activationKey: 'PLX-CLIENT-LOCAL',
      expiresAt: new Date(p.expiresAt),
      isAdmin: false,
      gracePeriodDays: 0,
    },
  };
}

/** Just validate a license file (used when uploading a new one, before setting password) */
export async function validateNewLicenseFile(licenseContent: string): Promise<LoginResult> {
  const machineId = await getMachineId();
  const result = await validateLicenseFile(licenseContent, machineId);
  if (!result.valid) {
    return { success: false, error: result.error };
  }
  return { success: true };
}

/** Clear profile entirely (Reset) */
export async function resetProfile(): Promise<void> {
  try {
    await (window as any).electronAPI?.profileDelete?.();
  } catch {}
}

/** Stub — no longer needed */
export async function fetchNotifications(): Promise<{ id: string; message: string; created_at: string }[]> {
  return [];
}

/** Stub — no longer needed */
export async function markNotificationRead(): Promise<void> { }

/** Stub — no longer needed */
export async function logLogin(): Promise<void> { }

/**
 * Calculate license status from session.
 */
export function getLicenseStatus(session: LicenseSession): {
  daysRemaining: number;
  isExpired: boolean;
  isInGrace: boolean;
  isHardLocked: boolean;
  status: 'valid' | 'warning' | 'critical' | 'grace' | 'locked';
} {
  if (session.isAdmin) {
    return { daysRemaining: 9999, isExpired: false, isInGrace: false, isHardLocked: false, status: 'valid' };
  }
  const now = new Date();
  const diff = session.expiresAt.getTime() - now.getTime();
  const daysRemaining = Math.ceil(diff / (1000 * 60 * 60 * 24));
  const isExpired = daysRemaining <= 0;
  return {
    daysRemaining,
    isExpired,
    isInGrace: false,
    isHardLocked: isExpired,
    status: isExpired ? 'locked' : daysRemaining <= 7 ? 'critical' : daysRemaining <= 30 ? 'warning' : 'valid',
  };
}

