
import React, { useMemo, useState } from 'react';
import type { SchedulingTaskData } from '../types';

interface AllTeamsStatusModalProps {
    isOpen: boolean;
    onClose: () => void;
    allScheduledTasks: SchedulingTaskData[];
    involvedDisciplines: string[];
    maxHours: number;
    schedulingDate: string | null;
    checkAvailabilityInterval?: { start: Date; end: Date } | null;
    /** Pass true only when the user has selected a start date */
    hasStartDate?: boolean;
    shiftStartTime?: string;
    shutdownStart?: string;
    shutdownEnd?: string;
    /** Called when user picks a team from this page — returns to assistant with team pre-selected */
    onSelectTeam?: (discipline: string, teamType: string) => void;
    /** Total hours required to be scheduled per discipline */
    requiredHoursPerDiscipline?: Record<string, number>;
}

// ─── helpers ────────────────────────────────────────────────────────────────

const fmt = (d: Date) =>
    d.toLocaleTimeString('fr-FR', { hour: '2-digit', minute: '2-digit' });

// FIX #2: Use LOCAL date components to avoid UTC offset producing wrong day
const isoDate = (d: Date): string => {
    const y = d.getFullYear();
    const mo = String(d.getMonth() + 1).padStart(2, '0');
    const da = String(d.getDate()).padStart(2, '0');
    return `${y}-${mo}-${da}`;
};

const fmtDate = (iso: string) => {
    // FIX #2: parse as LOCAL date, not UTC
    const d = new Date(iso + 'T00:00:00');
    return d.toLocaleDateString('fr-FR', { weekday: 'short', day: '2-digit', month: 'short' });
};

// FIX #2: getDaysInRange uses local dates, not UTC
function getDaysInRange(startIso: string, endIso: string): string[] {
    const days: string[] = [];
    // Parse as LOCAL time
    const cur = new Date(startIso + 'T00:00:00');
    const fin = new Date(endIso + 'T00:00:00');
    while (cur <= fin) {
        days.push(isoDate(cur));
        cur.setDate(cur.getDate() + 1);
    }
    return days;
}

function overlapHours(
    taskStart: Date, taskEnd: Date,
    winStart: Date, winEnd: Date
): number {
    const ms = Math.max(0,
        Math.min(taskEnd.getTime(), winEnd.getTime()) -
        Math.max(taskStart.getTime(), winStart.getTime())
    );
    return ms / 3_600_000;
}

// ─── types ──────────────────────────────────────────────────────────────────

interface TeamDaySlot {
    teamName: string;
    teamType: string;
    discipline: string;
    manpower: number;
    usedHours: number;
    freeHours: number;
    status: 'LIBRE' | 'PARTIEL' | 'PLEINE' | 'MEILLEUR';
    isAutoGenerated?: boolean;
    tasks: Array<{
        id: number;
        action: string;
        equipment: string;
        start: Date;
        end: Date;
        duree: number;
        manpower: number;
    }>;
}

// ─── sub-components ──────────────────────────────────────────────────────────

const StatusPill: React.FC<{ status: TeamDaySlot['status']; small?: boolean }> = ({ status, small }) => {
    const map: Record<TeamDaySlot['status'], { bg: string; text: string; label: string; dot: string }> = {
        LIBRE:    { bg: 'bg-emerald-500/15 border border-emerald-500/30', text: 'text-emerald-400', label: 'LIBRE',   dot: 'bg-emerald-400' },
        PARTIEL:  { bg: 'bg-amber-500/15 border border-amber-500/30',    text: 'text-amber-400',   label: 'PARTIEL', dot: 'bg-amber-400' },
        PLEINE:   { bg: 'bg-red-500/15 border border-red-500/30',        text: 'text-red-400',     label: 'PLEINE',  dot: 'bg-red-400' },
        MEILLEUR: { bg: 'bg-indigo-500/15 border border-indigo-500/30',  text: 'text-indigo-300',  label: '⭐ TOP',  dot: 'bg-indigo-400' },
    };
    const s = map[status];
    return (
        <span className={`inline-flex items-center gap-1.5 rounded-lg px-2 py-0.5 font-black uppercase tracking-wider ${small ? 'text-[9px]' : 'text-[10px]'} ${s.bg} ${s.text}`}>
            <span className={`w-1.5 h-1.5 rounded-full flex-shrink-0 ${s.dot}`} />
            {s.label}
        </span>
    );
};

const BarFill: React.FC<{ pct: number; status: TeamDaySlot['status'] }> = ({ pct, status }) => {
    const color = { LIBRE: 'bg-emerald-500', PARTIEL: 'bg-amber-500', PLEINE: 'bg-red-500', MEILLEUR: 'bg-indigo-500' }[status];
    return (
        <div className="h-1.5 w-full rounded-full bg-white/[0.06] overflow-hidden mt-2">
            <div className={`h-full rounded-full transition-all duration-500 ${color}`} style={{ width: `${Math.min(100, pct)}%`, opacity: 0.8 }} />
        </div>
    );
};

const TaskRow: React.FC<{ task: TeamDaySlot['tasks'][0] }> = ({ task }) => (
    <div className="grid grid-cols-[1fr_auto_auto_auto] gap-3 items-center py-2 border-b border-white/[0.04] last:border-0 hover:bg-white/[0.02] rounded-lg px-2 transition-colors">
        <div className="min-w-0">
            <p className="text-[11px] font-semibold text-slate-200 truncate leading-tight">{task.action}</p>
            {task.equipment && <p className="text-[10px] text-slate-500 truncate mt-0.5">{task.equipment}</p>}
        </div>
        <div className="text-right shrink-0">
            <p className="text-[10px] font-mono text-slate-400">{fmt(task.start)}</p>
            <p className="text-[10px] font-mono text-slate-500">→ {fmt(task.end)}</p>
        </div>
        <span className="text-[10px] font-black text-slate-300 font-mono shrink-0">{task.duree.toFixed(1)}h</span>
        <span className="text-[10px] text-slate-500 shrink-0">{task.manpower}p</span>
    </div>
);

// ─── FIX #4: Team Detail Popup ────────────────────────────────────────────────

const TeamDetailPopup: React.FC<{
    slot: TeamDaySlot;
    maxHours: number;
    activeDay: string;
    onClose: () => void;
}> = ({ slot, maxHours, activeDay, onClose }) => {
    const pct = maxHours > 0 ? (slot.usedHours / maxHours) * 100 : 0;
    const barColor = { LIBRE: 'from-emerald-500 to-emerald-400', PARTIEL: 'from-amber-500 to-amber-400', PLEINE: 'from-red-500 to-red-400', MEILLEUR: 'from-indigo-500 to-indigo-400' }[slot.status];

    return (
        <div
            className="fixed inset-0 z-[400] flex items-center justify-center p-4"
            style={{ background: 'rgba(0,0,0,0.8)', backdropFilter: 'blur(16px)' }}
            onClick={onClose}
        >
            <div
                className="w-full max-w-4xl rounded-[2.5rem] border border-white/[0.12] overflow-hidden shadow-[0_30px_100px_rgba(0,0,0,0.9)] flex flex-col max-h-[90vh]"
                style={{ background: 'linear-gradient(135deg,rgba(15,20,40,0.98),rgba(8,12,28,0.98))' }}
                onClick={e => e.stopPropagation()}
            >
                {/* Header */}
                <div className="px-8 pt-7 pb-5 border-b border-white/[0.08] bg-white/[0.02]">
                    <div className="flex items-start justify-between gap-4">
                        <div className="flex-1 min-w-0">
                            <div className="flex items-center gap-3 flex-wrap">
                                <h2 className="text-xl font-black text-white truncate tracking-tight">{slot.teamName}</h2>
                                <StatusPill status={slot.status} />
                            </div>
                            <p className="text-xs font-semibold text-slate-400 mt-1.5 uppercase tracking-wider">{slot.discipline} · <span className="text-indigo-400">{fmtDate(activeDay)}</span></p>
                        </div>
                        <button
                            type="button"
                            onClick={onClose}
                            className="w-10 h-10 rounded-2xl flex items-center justify-center bg-white/[0.06] hover:bg-white/[0.12] hover:text-white transition-all flex-shrink-0 text-slate-400 border border-white/5 active:scale-95"
                        >
                            <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2.5}>
                                <path strokeLinecap="round" strokeLinejoin="round" d="M6 18L18 6M6 6l12 12" />
                            </svg>
                        </button>
                    </div>

                    {/* Capacity bar */}
                    <div className="mt-5">
                        <div className="flex justify-between text-xs mb-2">
                            <span className="text-slate-400 font-medium">
                                <span className="font-black text-white text-sm font-mono">{slot.usedHours.toFixed(1)}h</span> utilisées
                            </span>
                            <span className="text-slate-400 font-medium">
                                <span className="font-black text-emerald-400 text-sm font-mono">{slot.freeHours.toFixed(1)}h</span> libres / {maxHours}h max
                            </span>
                        </div>
                        <div className="h-3 w-full rounded-full bg-white/[0.06] overflow-hidden p-0.5 border border-white/[0.05]">
                            <div
                                className={`h-full rounded-full bg-gradient-to-r ${barColor} transition-all duration-500 shadow-sm`}
                                style={{ width: `${Math.min(100, pct)}%` }}
                            />
                        </div>
                    </div>
                </div>

                {/* Stats row */}
                <div className="grid grid-cols-3 gap-4 px-8 py-5 border-b border-white/[0.06] bg-black/30">
                    <div className="text-center p-3 rounded-2xl bg-white/[0.02] border border-white/[0.04]">
                        <p className="text-2xl font-black text-white font-mono">{slot.manpower}</p>
                        <p className="text-[10px] text-slate-400 uppercase tracking-widest font-bold mt-1">Personnes en poste</p>
                    </div>
                    <div className="text-center p-3 rounded-2xl bg-white/[0.02] border border-white/[0.04]">
                        <p className="text-2xl font-black text-white font-mono">{slot.tasks.length}</p>
                        <p className="text-[10px] text-slate-400 uppercase tracking-widest font-bold mt-1">Interventions du jour</p>
                    </div>
                    <div className="text-center p-3 rounded-2xl bg-white/[0.02] border border-white/[0.04]">
                        <p className="text-2xl font-black text-white font-mono">{slot.usedHours.toFixed(1)}h</p>
                        <p className="text-[10px] text-slate-400 uppercase tracking-widest font-bold mt-1">Charge Totale (H-H)</p>
                    </div>
                </div>

                {/* Visual 24h Timeline */}
                <div className="px-8 py-5 border-b border-white/[0.06] bg-slate-950/40">
                    <div className="flex justify-between text-[10px] font-black uppercase tracking-wider text-slate-400 mb-3">
                        <span className="flex items-center gap-1.5"><span className="w-2 h-2 rounded-full bg-indigo-500 animate-pulse" /> ⏱️ Timeline de la journée (00h — 24h)</span>
                        <span>{slot.tasks.length} tâche(s) planifiée(s)</span>
                    </div>
                    <div className="relative h-8 w-full rounded-2xl bg-white/[0.03] border border-white/[0.08] overflow-hidden flex items-center shadow-inner">
                        {[0, 4, 8, 12, 16, 20, 24].map(h => (
                            <div key={h} className="absolute top-0 bottom-0 border-l border-white/[0.08] flex items-end pb-1 pl-1.5 pointer-events-none z-10" style={{ left: `${(h / 24) * 100}%` }}>
                                <span className="text-[9px] font-mono font-bold text-slate-500">{h}h</span>
                            </div>
                        ))}
                        {slot.tasks.map((t, i) => {
                            const startH = t.start.getHours() + t.start.getMinutes() / 60;
                            const endH = t.end.getHours() + t.end.getMinutes() / 60;
                            const leftPct = Math.max(0, Math.min(100, (startH / 24) * 100));
                            const dur = endH > startH ? endH - startH : 24 - startH;
                            const widthPct = Math.max(2, Math.min(100 - leftPct, (dur / 24) * 100));
                            const colors = [
                                'bg-sky-500/80 border-sky-400/60 text-sky-100',
                                'bg-indigo-500/80 border-indigo-400/60 text-indigo-100',
                                'bg-purple-500/80 border-purple-400/60 text-purple-100',
                                'bg-emerald-500/80 border-emerald-400/60 text-emerald-100',
                                'bg-amber-500/80 border-amber-400/60 text-amber-100'
                            ];
                            return (
                                <div
                                    key={i}
                                    className={`absolute h-6 rounded-xl border text-[9px] font-black px-2 flex items-center justify-between overflow-hidden shadow-md transition-all hover:scale-[1.03] hover:z-20 cursor-default ${colors[i % colors.length]}`}
                                    style={{ left: `${leftPct}%`, width: `${widthPct}%` }}
                                    title={`${t.action} (${fmt(t.start)} — ${fmt(t.end)})`}
                                >
                                    <span className="truncate">{t.action}</span>
                                    <span className="font-mono ml-1 opacity-90">{t.duree.toFixed(1)}h</span>
                                </div>
                            );
                        })}
                    </div>
                </div>

                {/* Task list */}
                <div className="px-8 py-5 flex-1 overflow-y-auto custom-scrollbar">
                    {slot.tasks.length === 0 ? (
                        <div className="text-center py-12 opacity-50">
                            <div className="w-16 h-16 rounded-3xl bg-white/[0.04] border border-white/[0.08] flex items-center justify-center mx-auto mb-3">
                                <svg xmlns="http://www.w3.org/2000/svg" className="w-8 h-8 text-slate-500" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2" />
                                </svg>
                            </div>
                            <p className="text-slate-400 text-sm font-bold">Aucune tâche assignée pour ce jour</p>
                            <p className="text-slate-600 text-xs mt-1">L'équipe est entièrement disponible sur cette période.</p>
                        </div>
                    ) : (
                        <>
                            <p className="text-[10px] font-black uppercase tracking-widest text-slate-400 mb-3 flex items-center justify-between">
                                <span>Détail complet des tâches ({slot.tasks.length})</span>
                                <span className="text-indigo-400 font-normal lowercase italic">classées chronologiquement</span>
                            </p>
                            <div className="space-y-2">
                                {slot.tasks.map((t, i) => (
                                    <div key={i} className="grid grid-cols-[1fr_auto_auto_auto] gap-4 items-center py-3 px-4 rounded-2xl bg-white/[0.03] hover:bg-white/[0.06] transition-all border border-white/[0.05] group">
                                        <div className="min-w-0">
                                            <p className="text-sm font-bold text-white truncate group-hover:text-indigo-300 transition-colors">{t.action}</p>
                                            {t.equipment && <p className="text-xs text-slate-400 truncate mt-0.5 flex items-center gap-1"><span>🔧</span> {t.equipment}</p>}
                                        </div>
                                        <div className="text-right shrink-0 bg-black/40 px-3 py-1.5 rounded-xl border border-white/5">
                                            <div className="flex items-center gap-1.5 text-xs font-mono font-bold text-slate-300">
                                                <span className="text-emerald-400">{fmt(t.start)}</span>
                                                <span className="text-slate-600">→</span>
                                                <span className="text-blue-400">{fmt(t.end)}</span>
                                            </div>
                                        </div>
                                        <span className="text-xs font-black text-indigo-300 font-mono shrink-0 bg-indigo-500/15 border border-indigo-500/30 px-2.5 py-1 rounded-xl shadow-sm">{t.duree.toFixed(1)}h</span>
                                        <span className="text-xs font-bold text-slate-300 shrink-0 bg-white/[0.05] border border-white/[0.08] px-2.5 py-1 rounded-xl flex items-center gap-1">👤 <span className="font-mono text-white">{t.manpower}</span></span>
                                    </div>
                                ))}
                            </div>
                        </>
                    )}
                </div>
            </div>
        </div>
    );
};

// ─── team card ────────────────────────────────────────────────────────────────

const TeamDayCard: React.FC<{
    slot: TeamDaySlot;
    maxHours: number;
    isHighlighted: boolean;
    isExpanded: boolean;
    canAssign: boolean;
    onToggle: (e: React.MouseEvent) => void;
    onAssign: (e: React.MouseEvent) => void;
    onDetailClick: () => void;
}> = ({ slot, maxHours, isHighlighted, isExpanded, canAssign, onToggle, onAssign, onDetailClick }) => {
    const pct = maxHours > 0 ? (slot.usedHours / maxHours) * 100 : 0;
    const canBePicked = canAssign && slot.status !== 'PLEINE';

    return (
        <div
            className={`rounded-2xl border transition-all duration-300 overflow-hidden cursor-pointer group ${
                isHighlighted
                    ? 'border-indigo-500/40 bg-indigo-500/5 shadow-[0_0_24px_rgba(99,102,241,0.12)]'
                    : slot.status === 'PLEINE'
                        ? 'border-red-500/20 bg-red-500/[0.03] hover:border-red-500/30'
                        : slot.status === 'LIBRE' || slot.status === 'MEILLEUR'
                            ? 'border-emerald-500/20 bg-emerald-500/[0.03] hover:border-emerald-500/30'
                            : 'border-white/[0.06] bg-white/[0.02] hover:border-white/[0.10]'
            }`}
            onClick={e => { e.stopPropagation(); onDetailClick(); }}
        >
            {/* Header row */}
            <div className="p-4">
                <div className="flex items-start justify-between gap-3">
                    {/* Name + badge */}
                    <div className="min-w-0 flex-1">
                        <div className="flex items-center gap-2 flex-wrap">
                            <span className="font-bold text-slate-200 text-sm leading-tight group-hover:text-white transition-colors">{slot.teamName}</span>
                            <StatusPill status={slot.status} small />
                            {slot.isAutoGenerated && (
                                <span className="bg-purple-500/15 border border-purple-500/30 text-purple-300 text-[9px] font-black uppercase tracking-wider px-2 py-0.5 rounded-lg flex items-center gap-1 shadow-sm">
                                    ⚡ Rotation
                                </span>
                            )}
                        </div>
                        <p className="text-[10px] text-slate-500 mt-1">
                            👤 {slot.manpower} pers · {slot.tasks.length} tâche{slot.tasks.length !== 1 ? 's' : ''}
                        </p>
                    </div>

                    {/* Right side: hours + actions */}
                    <div className="flex items-center gap-2 shrink-0">
                        <div className="text-right">
                            <p className={`text-sm font-black font-mono ${slot.freeHours > 0.1 ? 'text-emerald-400' : 'text-red-400'}`}>
                                {slot.freeHours.toFixed(1)}h
                            </p>
                            <p className="text-[9px] text-slate-500 uppercase tracking-wider">libre</p>
                        </div>

                        {/* Assign button */}
                        {canBePicked && (
                            <button
                                type="button"
                                onClick={e => { e.stopPropagation(); onAssign(e); }}
                                className="flex items-center gap-1.5 text-[10px] font-black uppercase tracking-widest bg-emerald-500/20 hover:bg-emerald-500/35 border border-emerald-500/40 text-emerald-300 hover:text-white px-3 py-1.5 rounded-xl transition-all active:scale-95 whitespace-nowrap"
                            >
                                <svg xmlns="http://www.w3.org/2000/svg" className="w-3 h-3" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2.5}>
                                    <path strokeLinecap="round" strokeLinejoin="round" d="M5 13l4 4L19 7" />
                                </svg>
                                Assigner
                            </button>
                        )}

                        {/* Expand chevron */}
                        <button
                            type="button"
                            onClick={e => { e.stopPropagation(); onToggle(e); }}
                            className="p-1 rounded-lg hover:bg-white/10 transition-colors"
                        >
                            <svg className={`w-4 h-4 text-slate-500 transition-transform duration-300 ${isExpanded ? 'rotate-180' : ''}`}
                                fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                                <path strokeLinecap="round" strokeLinejoin="round" d="M19 9l-7 7-7-7" />
                            </svg>
                        </button>
                    </div>
                </div>

                {/* Progress bar */}
                <BarFill pct={pct} status={slot.status} />
                <div className="flex justify-between mt-1">
                    <span className="text-[9px] text-slate-600">{slot.usedHours.toFixed(1)}h utilisées</span>
                    <span className="text-[9px] text-slate-600">{maxHours}h max</span>
                </div>
            </div>

            {/* Expanded task list */}
            {isExpanded && (
                <div
                    className="border-t border-white/[0.06] px-4 pb-3 pt-2 bg-black/20"
                    onClick={e => e.stopPropagation()}
                >
                    {slot.tasks.length === 0 ? (
                        <p className="text-[11px] text-slate-500 py-3 text-center italic">Aucune tâche ce jour</p>
                    ) : (
                        <div>
                            <p className="text-[9px] font-black uppercase tracking-widest text-slate-600 mb-2">Tâches assignées</p>
                            {slot.tasks.map(t => <TaskRow key={t.id} task={t} />)}
                        </div>
                    )}
                </div>
            )}
        </div>
    );
};

// ─── main component ──────────────────────────────────────────────────────────

export const AllTeamsStatusModal: React.FC<AllTeamsStatusModalProps> = ({
    isOpen,
    onClose,
    allScheduledTasks,
    involvedDisciplines,
    maxHours,
    schedulingDate,
    checkAvailabilityInterval,
    hasStartDate = false,
    shiftStartTime = '07:00',
    shutdownStart,
    shutdownEnd,
    onSelectTeam,
    requiredHoursPerDiscipline,
}) => {
    const [showFreeOnly, setShowFreeOnly] = useState(false);
    const [hideRotationTeams, setHideRotationTeams] = useState(true);
    const [expandedKey, setExpandedKey] = useState<string | null>(null);
    const [disciplineFilter, setDisciplineFilter] = useState<string>('Toutes');
    const [assignedFeedback, setAssignedFeedback] = useState<string | null>(null);
    // FIX #4: detail popup state
    const [detailSlot, setDetailSlot] = useState<TeamDaySlot | null>(null);

    // Auto-filter by involved disciplines when modal opens
    React.useEffect(() => {
        if (isOpen && involvedDisciplines && involvedDisciplines.length === 1) {
            setDisciplineFilter(involvedDisciplines[0]);
        } else {
            setDisciplineFilter('Toutes');
        }
    }, [isOpen, involvedDisciplines]);

    // FIX #2: Build list of shutdown days using local date strings
    const shutdownDays = useMemo(() => {
        if (shutdownStart && shutdownEnd) {
            const startIso = shutdownStart.split('T')[0];
            const endIso = shutdownEnd.split('T')[0];
            return getDaysInRange(startIso, endIso);
        }
        if (schedulingDate) {
            const baseIso = schedulingDate.split('T')[0];
            const base = new Date(baseIso + 'T00:00:00');
            const startD = new Date(base); startD.setDate(base.getDate() - 3);
            const endD = new Date(base); endD.setDate(base.getDate() + 7);
            return getDaysInRange(isoDate(startD), isoDate(endD));
        }
        return [];
    }, [shutdownStart, shutdownEnd, schedulingDate]);

    // Auto-select the day matching schedulingDate
    const initialDayIdx = useMemo(() => {
        if (!schedulingDate || shutdownDays.length === 0) return 0;
        const target = schedulingDate.split('T')[0];
        const idx = shutdownDays.indexOf(target);
        return idx >= 0 ? idx : 0;
    }, [schedulingDate, shutdownDays]);

    const [activeDayIdx, setActiveDayIdx] = useState(initialDayIdx);
    React.useEffect(() => { setActiveDayIdx(initialDayIdx); }, [initialDayIdx]);

    const activeDay = shutdownDays[activeDayIdx] ?? null;

    // Strict discipline list based on involvedDisciplines if provided
    const allDisciplines = useMemo(() => {
        if (involvedDisciplines && involvedDisciplines.length > 0) {
            if (involvedDisciplines.length === 1) return involvedDisciplines;
            return ['Toutes', ...involvedDisciplines.slice().sort()];
        }
        const set = new Set<string>();
        allScheduledTasks.forEach(t => { if (t.DISCIPLINE) set.add(t.DISCIPLINE); });
        return ['Toutes', ...Array.from(set).sort()];
    }, [involvedDisciplines, allScheduledTasks]);

    // Build slot data for the active day
    const daySlots = useMemo((): TeamDaySlot[] => {
        if (!activeDay) return [];

        const [shH, shM] = shiftStartTime.split(':').map(Number);
        const winStart = new Date(activeDay + 'T00:00:00');
        winStart.setHours(shH, shM, 0, 0);
        const winEnd = new Date(winStart.getTime() + maxHours * 3_600_000);

        // Also check against full 24h day to properly catch overnight shifts (e.g. Shift 2: 20:00 to 08:00)
        const dayStart = new Date(activeDay + 'T00:00:00');
        const dayEnd = new Date(activeDay + 'T23:59:59');

        // Build team map — expand shiftAssignments into separate team entries
        const teamMap = new Map<string, { discipline: string; tasks: SchedulingTaskData[]; isAutoGenerated: boolean }>();
        allScheduledTasks.forEach(task => {
            if (!task.isScheduled) return;

            if (task.shiftAssignments && task.shiftAssignments.length > 0) {
                task.shiftAssignments.forEach(shift => {
                    const shiftKey = `${task.DISCIPLINE} ${shift.teamType}`;
                    if (!teamMap.has(shiftKey)) teamMap.set(shiftKey, { discipline: task.DISCIPLINE, tasks: [], isAutoGenerated: true });
                    else teamMap.get(shiftKey)!.isAutoGenerated = true;

                    const shiftStart = shift.startTime
                        ? (shift.startTime instanceof Date ? shift.startTime : new Date(shift.startTime))
                        : new Date((shift as any).start);
                    const shiftEnd = shift.endTime
                        ? (shift.endTime instanceof Date ? shift.endTime : new Date(shift.endTime))
                        : new Date((shift as any).end);
                    const shiftTask: SchedulingTaskData = {
                        ...task,
                        "TYPE D'EQUIPE": shift.teamType,
                        'START DATE': shiftStart,
                        'END DATE': shiftEnd,
                        DUREE: shift.durationH,
                        EFFECTIF: shift.manpower || task.EFFECTIF || 1,
                        'GLOBAL TASKS': `${task['GLOBAL TASKS']} [S${shift.shiftIndex}]`,
                    };
                    teamMap.get(shiftKey)!.tasks.push(shiftTask);
                });
                return;
            }

            if (!task["TYPE D'EQUIPE"]) return;
            const primaryKey = `${task.DISCIPLINE} ${task["TYPE D'EQUIPE"]}`;
            const isRot = /^Équipe\s+[A-Z]$/i.test(task["TYPE D'EQUIPE"]);
            if (!teamMap.has(primaryKey)) teamMap.set(primaryKey, { discipline: task.DISCIPLINE, tasks: [], isAutoGenerated: isRot });
            else if (isRot) teamMap.get(primaryKey)!.isAutoGenerated = true;

            teamMap.get(primaryKey)!.tasks.push(task);
        });

        const checkStart = checkAvailabilityInterval?.start ?? null;
        const checkEnd = checkAvailabilityInterval?.end ?? null;

        let slots: TeamDaySlot[] = Array.from(teamMap.entries()).map(([teamName, { discipline, tasks, isAutoGenerated }]) => {
            const teamType = teamName.substring(discipline.length + 1);

            // Check overlap against the full 24h day so overnight shifts are never missed
            const usedHours = tasks
                .filter(t => t['START DATE'] && t['END DATE'])
                .reduce((sum, t) => {
                    const h = overlapHours(t['START DATE'] as Date, t['END DATE'] as Date, dayStart, dayEnd);
                    return sum + h;
                }, 0);

            const freeHours = Math.max(0, maxHours - usedHours);
            const manpower = tasks.length > 0 ? Math.max(...tasks.map(t => t.EFFECTIF || 0)) : 0;

            // Tasks active at any point on this day
            const dayTasks = tasks
                .filter(t => t['START DATE'] && t['END DATE'] &&
                    overlapHours(t['START DATE'] as Date, t['END DATE'] as Date, dayStart, dayEnd) > 0)
                .map(t => ({
                    id: t.id,
                    action: t['GLOBAL TASKS'] || '',
                    equipment: t['Nom Equipement'] || '',
                    start: t['START DATE']!,
                    end: t['END DATE']!,
                    duree: overlapHours(t['START DATE']!, t['END DATE']!, dayStart, dayEnd),
                    manpower: t.EFFECTIF || 0,
                }))
                .sort((a, b) => a.start.getTime() - b.start.getTime());

            const reqHours = (requiredHoursPerDiscipline && requiredHoursPerDiscipline[discipline]) ||
                (checkStart && checkEnd ? overlapHours(checkStart, checkEnd, dayStart, dayEnd) : 0);

            let status: TeamDaySlot['status'] = 'LIBRE';
            if (usedHours + reqHours > maxHours + 0.05 || usedHours >= maxHours - 0.1) {
                status = 'PLEINE';
            } else if (usedHours > 0) {
                status = 'PARTIEL';
            }

            // Shift Locking: if targeting a specific slot, check against ALL assigned tasks across the team's entire timeline
            if (checkStart && checkEnd) {
                const isLocked = tasks.some(t => {
                    if (!t['START DATE'] || !t['END DATE']) return false;
                    return t['START DATE'] < checkEnd && t['END DATE'] > checkStart;
                });
                if (isLocked) status = 'PLEINE';
            }

            return { teamName, teamType, discipline, manpower, usedHours, freeHours, status, isAutoGenerated, tasks: dayTasks };
        });

        const available = slots.filter(s => s.status === 'LIBRE');
        if (available.length > 0) {
            const best = available.reduce((a, b) => a.freeHours < b.freeHours ? a : b);
            best.status = 'MEILLEUR';
        }

        // Strict Discipline Filtering
        if (disciplineFilter !== 'Toutes') {
            slots = slots.filter(s => s.discipline === disciplineFilter);
        } else if (involvedDisciplines && involvedDisciplines.length > 0) {
            slots = slots.filter(s => involvedDisciplines.includes(s.discipline));
        }
        if (showFreeOnly) {
            slots = slots.filter(s => s.status !== 'PLEINE');
        }
        if (hideRotationTeams) {
            slots = slots.filter(s => !s.isAutoGenerated);
        }

        return slots.sort((a, b) => {
            const order = { MEILLEUR: 0, LIBRE: 1, PARTIEL: 2, PLEINE: 3 };
            return order[a.status] - order[b.status];
        });
    }, [activeDay, allScheduledTasks, maxHours, shiftStartTime, checkAvailabilityInterval, disciplineFilter, showFreeOnly, hideRotationTeams, involvedDisciplines]);

    if (!isOpen) return null;

    const targetDayKey = schedulingDate ? schedulingDate.split('T')[0] : null;
    const stats = {
        libre: daySlots.filter(s => s.status === 'LIBRE' || s.status === 'MEILLEUR').length,
        partiel: daySlots.filter(s => s.status === 'PARTIEL').length,
        pleine: daySlots.filter(s => s.status === 'PLEINE').length,
    };

    const handleAssign = (slot: TeamDaySlot, e: React.MouseEvent) => {
        e.stopPropagation();
        if (onSelectTeam) {
            onSelectTeam(slot.discipline, slot.teamType);
            setAssignedFeedback(slot.teamName);
            setTimeout(() => { onClose(); }, 600);
        }
    };

    return (
        <div
            className="fixed inset-0 z-[200] flex flex-col"
            style={{ background: 'rgba(4,7,18,0.97)', backdropFilter: 'blur(24px)' }}
            onClick={e => e.stopPropagation()}
        >
            {/* FIX #4: Detail popup overlay */}
            {detailSlot && activeDay && (
                <TeamDetailPopup
                    slot={detailSlot}
                    maxHours={maxHours}
                    activeDay={activeDay}
                    onClose={() => setDetailSlot(null)}
                />
            )}

            {/* ── TOP HEADER ─────────────────────────────────────────────── */}
            <header
                className="flex items-center justify-between px-8 py-4 border-b border-white/[0.07] flex-shrink-0"
                onClick={e => e.stopPropagation()}
            >
                <div className="flex items-center gap-4">
                    {/* Back button */}
                    <button
                        type="button"
                        onClick={(e) => { e.stopPropagation(); onClose(); }}
                        className="flex items-center gap-2 text-slate-400 hover:text-white transition-all group"
                    >
                        <div className="w-9 h-9 rounded-xl flex items-center justify-center bg-white/[0.05] group-hover:bg-white/[0.1] transition-all border border-white/[0.08]">
                            <svg xmlns="http://www.w3.org/2000/svg" className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2.5}>
                                <path strokeLinecap="round" strokeLinejoin="round" d="M10 19l-7-7m0 0l7-7m-7 7h18" />
                            </svg>
                        </div>
                        <span className="text-sm font-semibold hidden md:block">Retour à l'Assistant</span>
                    </button>

                    <div className="w-px h-8 bg-white/[0.07]" />

                    <div className="flex items-center gap-3">
                        <div className="w-10 h-10 rounded-xl flex items-center justify-center flex-shrink-0"
                            style={{ background: 'linear-gradient(135deg,#6366f1,#4f46e5)' }}>
                            <svg xmlns="http://www.w3.org/2000/svg" className="w-5 h-5 text-white" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                                <path strokeLinecap="round" strokeLinejoin="round" d="M8 7V3m8 4V3m-9 8h10M5 21h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z" />
                            </svg>
                        </div>
                        <div>
                            <p className="text-[10px] font-bold tracking-[0.2em] uppercase text-indigo-400">Planification Intelligente</p>
                            <h1 className="text-xl font-black text-white tracking-tight">Disponibilité des Équipes</h1>
                        </div>
                    </div>
                </div>

                {/* Legend */}
                <div className="hidden lg:flex items-center gap-5 text-[10px] font-bold uppercase tracking-widest">
                    <span className="flex items-center gap-1.5 text-emerald-400"><span className="w-2 h-2 rounded-full bg-emerald-400" />Libre</span>
                    <span className="flex items-center gap-1.5 text-amber-400"><span className="w-2 h-2 rounded-full bg-amber-400" />Partiel</span>
                    <span className="flex items-center gap-1.5 text-red-400"><span className="w-2 h-2 rounded-full bg-red-400" />Pleine</span>
                    <span className="flex items-center gap-1.5 text-indigo-300"><span className="w-2 h-2 rounded-full bg-indigo-400" />⭐ Meilleur</span>
                    {onSelectTeam && (
                        <span className="flex items-center gap-1.5 text-emerald-300 bg-emerald-500/10 border border-emerald-500/20 px-3 py-1.5 rounded-xl">
                            ✓ Cliquez "Assigner" pour sélectionner une équipe
                        </span>
                    )}
                </div>
            </header>

            {/* ── ASSIGNED FEEDBACK TOAST ──────────────────────────────── */}
            {assignedFeedback && (
                <div className="absolute top-20 left-1/2 -translate-x-1/2 z-[210] bg-emerald-500 text-white font-black text-sm px-6 py-3 rounded-2xl shadow-2xl animate-bounce">
                    ✅ {assignedFeedback} assignée — retour à l'assistant…
                </div>
            )}

            {/* ── BODY ──────────────────────────────────────────────────── */}
            <div className="flex flex-1 overflow-hidden" onClick={e => e.stopPropagation()}>

                {/* ── LEFT: Day Navigator ── */}
                <aside className="w-56 flex-shrink-0 border-r border-white/[0.06] flex flex-col overflow-hidden">
                    <div className="px-4 py-3 border-b border-white/[0.06]">
                        <p className="text-[10px] font-black uppercase tracking-widest text-slate-500">Jours d'Arrêt</p>
                    </div>
                    <div className="overflow-y-auto flex-1 py-2">
                        {shutdownDays.length === 0 && (
                            <p className="text-[11px] text-slate-600 text-center py-6 italic">Paramètres requis</p>
                        )}
                        {shutdownDays.map((day, idx) => {
                            const isActive = idx === activeDayIdx;
                            const isTarget = day === targetDayKey;
                            return (
                                <button
                                    key={day}
                                    type="button"
                                    onClick={(e) => { e.stopPropagation(); setActiveDayIdx(idx); setExpandedKey(null); setDetailSlot(null); }}
                                    className={`w-full text-left px-4 py-2.5 transition-all duration-200 relative ${
                                        isActive
                                            ? 'bg-indigo-500/15 text-indigo-300'
                                            : 'text-slate-400 hover:bg-white/[0.04] hover:text-slate-200'
                                    }`}
                                >
                                    {isActive && <span className="absolute left-0 top-0 bottom-0 w-0.5 bg-indigo-500 rounded-r-full" />}
                                    <p className="text-[11px] font-bold capitalize">{fmtDate(day)}</p>
                                    {isTarget && (
                                        <span className="text-[9px] font-black uppercase tracking-wider text-indigo-400">← Créneau ciblé</span>
                                    )}
                                </button>
                            );
                        })}
                    </div>
                </aside>

                {/* ── RIGHT: Teams Panel ── */}
                <main className="flex-1 flex flex-col overflow-hidden" onClick={e => e.stopPropagation()}>

                    {/* Toolbar */}
                    <div className="px-6 py-3 border-b border-white/[0.06] bg-white/[0.01] flex items-center gap-4 flex-shrink-0 flex-wrap">
                        <div className="flex items-center gap-2 mr-auto">
                            <svg xmlns="http://www.w3.org/2000/svg" className="w-4 h-4 text-indigo-400" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                                <path strokeLinecap="round" strokeLinejoin="round" d="M8 7V3m8 4V3m-9 8h10M5 21h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z" />
                            </svg>
                            <span className="font-bold text-white capitalize">
                                {activeDay ? fmtDate(activeDay) : '—'}
                            </span>
                            {activeDay === targetDayKey && (
                                <span className="text-[9px] font-black uppercase tracking-wider bg-indigo-500/20 border border-indigo-500/30 text-indigo-300 px-2 py-0.5 rounded-lg">
                                    Jour ciblé
                                </span>
                            )}
                            <span className="text-[10px] text-slate-500 ml-2 font-mono">
                                {shiftStartTime} → {(() => {
                                    const [h, m] = shiftStartTime.split(':').map(Number);
                                    const e = new Date(0); e.setHours(h + maxHours, m);
                                    return `${String(e.getHours()).padStart(2,'0')}:${String(e.getMinutes()).padStart(2,'0')}`;
                                })()} ({maxHours}H)
                            </span>
                        </div>

                        {/* Stats */}
                        <div className="flex items-center gap-2">
                            <span className="text-[10px] font-black text-emerald-400 bg-emerald-500/10 border border-emerald-500/20 rounded-lg px-2.5 py-1">{stats.libre} Libres</span>
                            <span className="text-[10px] font-black text-amber-400 bg-amber-500/10 border border-amber-500/20 rounded-lg px-2.5 py-1">{stats.partiel} Partiels</span>
                            <span className="text-[10px] font-black text-red-400 bg-red-500/10 border border-red-500/20 rounded-lg px-2.5 py-1">{stats.pleine} Pleines</span>
                        </div>

                        {/* Discipline filter */}
                        <select
                            value={disciplineFilter}
                            onChange={e => { e.stopPropagation(); setDisciplineFilter(e.target.value); }}
                            className="bg-slate-900 border border-white/10 rounded-xl px-3 py-1.5 text-xs text-slate-300 focus:outline-none focus:border-indigo-500/50 transition-all"
                            onClick={e => e.stopPropagation()}
                        >
                            {allDisciplines.map(d => <option key={d} value={d}>{d}</option>)}
                        </select>

                        {/* Libres only toggle */}
                        <label className="flex items-center gap-2 cursor-pointer" onClick={e => e.stopPropagation()}>
                            <div
                                className={`relative w-9 h-5 rounded-full transition-colors ${showFreeOnly ? 'bg-indigo-500' : 'bg-white/10'}`}
                                onClick={(e) => { e.stopPropagation(); setShowFreeOnly(v => !v); }}
                            >
                                <div className={`absolute top-0.5 w-4 h-4 rounded-full bg-white shadow transition-transform ${showFreeOnly ? 'translate-x-4' : 'translate-x-0.5'}`} />
                            </div>
                            <span className="text-xs text-slate-300 whitespace-nowrap">Libres only</span>
                        </label>

                        {/* Masquer rotations toggle */}
                        <label className="flex items-center gap-2 cursor-pointer" onClick={e => e.stopPropagation()}>
                            <div
                                className={`relative w-9 h-5 rounded-full transition-colors ${hideRotationTeams ? 'bg-purple-600' : 'bg-white/10'}`}
                                onClick={(e) => { e.stopPropagation(); setHideRotationTeams(v => !v); }}
                            >
                                <div className={`absolute top-0.5 w-4 h-4 rounded-full bg-white shadow transition-transform ${hideRotationTeams ? 'translate-x-4' : 'translate-x-0.5'}`} />
                            </div>
                            <span className="text-xs text-slate-300 whitespace-nowrap">Masquer rotations</span>
                        </label>
                    </div>

                    {/* Gate: no start date */}
                    {!hasStartDate ? (
                        <div className="flex-1 flex flex-col items-center justify-center gap-6 p-8" onClick={e => e.stopPropagation()}>
                            <div className="w-20 h-20 rounded-3xl flex items-center justify-center"
                                style={{ background: 'linear-gradient(135deg,rgba(99,102,241,0.2),rgba(99,102,241,0.05))', border: '1px solid rgba(99,102,241,0.3)' }}>
                                <svg xmlns="http://www.w3.org/2000/svg" className="w-10 h-10 text-indigo-400" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={1.5}>
                                    <path strokeLinecap="round" strokeLinejoin="round" d="M12 9v3.75m9-.75a9 9 0 11-18 0 9 9 0 0118 0zm-9 3.75h.008v.008H12v-.008z" />
                                </svg>
                            </div>
                            <div className="text-center max-w-sm">
                                <p className="text-white font-black text-xl mb-2">Stratégie requise</p>
                                <p className="text-slate-400 text-sm leading-relaxed">
                                    Sélectionnez une <span className="text-indigo-300 font-semibold">date de démarrage</span> dans le formulaire pour activer le calendrier de disponibilité.
                                </p>
                            </div>
                            <button
                                type="button"
                                onClick={(e) => { e.stopPropagation(); onClose(); }}
                                className="flex items-center gap-2 bg-indigo-500/20 hover:bg-indigo-500/30 border border-indigo-500/30 text-indigo-300 font-bold text-sm px-5 py-2.5 rounded-xl transition-all"
                            >
                                <svg xmlns="http://www.w3.org/2000/svg" className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2.5}>
                                    <path strokeLinecap="round" strokeLinejoin="round" d="M10 19l-7-7m0 0l7-7m-7 7h18" />
                                </svg>
                                Retour à l'Assistant
                            </button>
                        </div>
                    ) : (
                        <div className="flex-1 overflow-y-auto p-6" onClick={e => e.stopPropagation()}>
                            {daySlots.length === 0 ? (
                                <div className="flex flex-col items-center justify-center h-full gap-4 opacity-50">
                                    <svg xmlns="http://www.w3.org/2000/svg" className="w-12 h-12 text-slate-600" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M17 20h5v-2a3 3 0 00-5.356-1.857M17 20H7m10 0v-2c0-.656-.126-1.283-.356-1.857M7 20H2v-2a3 3 0 015.356-1.857M7 20v-2c0-.656.126-1.283.356-1.857m0 0a5.002 5.002 0 019.288 0M15 7a3 3 0 11-6 0 3 3 0 016 0z" />
                                    </svg>
                                    <p className="text-slate-500 font-semibold">Aucune équipe pour ce jour</p>
                                </div>
                            ) : (
                                <div className="grid grid-cols-1 lg:grid-cols-2 xl:grid-cols-3 gap-4">
                                    {daySlots.map(slot => {
                                        const key = `${slot.teamName}-${activeDay}`;
                                        const isHighlighted = (activeDay === targetDayKey) && (slot.status === 'MEILLEUR');
                                        const canAssign = !!onSelectTeam && (involvedDisciplines.length === 0 || involvedDisciplines.includes(slot.discipline));
                                        return (
                                            <TeamDayCard
                                                key={key}
                                                slot={slot}
                                                maxHours={maxHours}
                                                isHighlighted={isHighlighted}
                                                isExpanded={expandedKey === key}
                                                canAssign={canAssign}
                                                onToggle={(e) => { e.stopPropagation(); setExpandedKey(expandedKey === key ? null : key); }}
                                                onAssign={(e) => handleAssign(slot, e)}
                                                onDetailClick={() => setDetailSlot(slot)}
                                            />
                                        );
                                    })}
                                </div>
                            )}
                        </div>
                    )}
                </main>
            </div>
        </div>
    );
};
